In [26]:
# Perceptron
import torch

class Perceptron:
    def __init__(self, w, b):
        # Initialize randomly the weights and bias
        self.w = w
        self.b = b

    def forward(self, x):
        return x @ self.w + self.b
    
    def backward(self, loss):
        
    

In [98]:
# AND gate outputs
X = torch.tensor([[0.,0.],
                  [0.,1.],
                  [1.,0.],
                  [1.,1.]])
y = torch.tensor([0,0,0,1])

percep = Perceptron(torch.tensor([1.,1.]) , torch.tensor(-1))

for i in range(10):
    ind = torch.randint(0,4,(1,))
    X_sample = X[ind]
    y_sample = y[ind]
    print(X_sample, ": ", y_sample)

tensor([[0., 1.]]) :  tensor([0])
tensor([[0., 0.]]) :  tensor([0])
tensor([[1., 1.]]) :  tensor([1])
tensor([[0., 0.]]) :  tensor([0])
tensor([[0., 1.]]) :  tensor([0])
tensor([[1., 0.]]) :  tensor([0])
tensor([[0., 1.]]) :  tensor([0])
tensor([[1., 1.]]) :  tensor([1])
tensor([[0., 1.]]) :  tensor([0])
tensor([[0., 0.]]) :  tensor([0])


In [95]:
X[torch.randint(0,4,(1,))]

tensor([[1., 1.]])